library(data.table)
library(dplyr)
library(purrr)
library(coloc)

ARGS <- commandArgs(trailingOnly = TRUE)
file1 = ARGS[1] # nominal file of cis-mediating eQTL (generated by tensorqtl)
file2 = ARGS[2] # nominal file of trans-eQTL (generated by omiga)
genefile1 = ARGS[3] # gene list of cis-mediating eQTL without header
genefile2 = ARGS[4] # gene list of trans-eQTL without header
tissue = ARGS[5] # tissue name
chrom = ARGS[6] # chromosome name
outfile = ARGS[7] # output file of coloc
if (!file.exists(file1)) { stop("Can not find the nominal file1") }
if (!file.exists(file2)) { stop("Can not find the nominal file2") }

# input qtl files
nominal1 = fread(file1, header = T)
nominal2 = fread(file2, header = T)
genelist1 = fread(genefile1, header = F)$V1
genelist2 = fread(genefile2, header = F)$V1

# extract genes
df1 = nominal1[phenotype_id %in% genelist1]
df2 = nominal2[pheno_id %in% genelist2]
sample_size = round(max(df1$ma_count / df1$af)/2)

# calculate the pph4
cis_genes <- unique(df1$phenotype_id)
trans_genes <- unique(df2$pheno_id)

for (cis_gene in cis_genes) {
  df_cis <- subset(df1, phenotype_id == cis_gene)
  for (trans_gene in trans_genes) {
    df_trans <- subset(df2, pheno_id == trans_gene)
    # ignore genes with missing data
    if (!nrow(df_cis) || any(is.na(df_cis[, .(slope, pval_nominal)]))) { next }
    if (!nrow(df_trans) || any(is.na(df_trans[, .(beta_g1, pval_g1)]))) { next }
    if (length(intersect(df_cis$variant_id, df_trans$variant_id)) == 0) { next }

    df1_coloc = list(beta=df_cis$slope, pvalues=df_cis$pval_nominal,
                    snp=df_cis$variant_id, type="quant", N=rep(sample_size, nrow(df_cis)),
                    MAF=as.numeric(ifelse(df_cis$af <= 0.5, df_cis$af, 1-df_cis$af)))
    df2_coloc = list(beta=df_trans$beta_g1, pvalues=df_trans$pval_g1,
                    snp=df_trans$variant_id, type="quant", N=rep(sample_size, nrow(df_trans)),
                    MAF=as.numeric(ifelse(df_trans$af <= 0.5, df_trans$af, 1-df_trans$af)))

    rm(my.res)
    my.res <- coloc.abf(dataset1=df1_coloc, dataset2=df2_coloc)
    if (!exists("my.res")) next

    cat(cis_gene, trans_gene, "\n")
    results=list(my.res$summary)
    as.data.frame(t(unlist(results))) -> results
    results$cis_gene = cis_gene
    results$trans_gene = trans_gene
    results$chrom = chrom
    results$tissue = tissue
    # columns: nsnps PP.H0.abf PP.H1.abf PP.H2.abf PP.H3.abf PP.H4.abf phenotype1 phenotype2 chrom tissue
    fwrite(results, outfile, append=TRUE, col.names=FALSE, sep="\t")
  }
}
