libpath = "/storage/public/home/2020060185/anaconda3/envs/rnaseq/lib/R/library"
library(data.table, lib.loc = libpath)
library(dplyr, lib.loc = libpath)
library(R.utils, lib.loc = libpath)
library(PCAForQTL)

# input data
ARGS <- commandArgs(trailingOnly = TRUE)
bed = ARGS[1] # TMM bed.gz file
prefix = ARGS[2] # prefix of output files
eigenvecfile = ARGS[3] # input genotype .eigenvec file generated by plink --pca
#covarfile = ARGS[4] # other known covariates such as sex
tis = strsplit(bed, "/")[[1]][1]
if (!file.exists(bed)) { stop("Can not find the tmm bed.gz file") }
if (!file.exists(eigenvecfile)) { stop("Can not find the genotype .eigenvec file") }
#if (!file.exists(covarfile)) { stop("Can not find other known covariates file") }

# input phenotype PCs
dataGeneExpressionFP<-fread(bed, header = T) #The first four columns are: #chr, start, end, and gene_id.
expr<-t(dataGeneExpressionFP[,-(1:4)])
dim(expr)
pheno_prcomp<-prcomp(expr,center=TRUE, scale.=TRUE) #This should take less than a minute.
pheno_PCs<-pheno_prcomp$x
dim(pheno_PCs)
pheno_importance<-summary(pheno_prcomp)$importance
pheno_PVEs<-pheno_importance[2,]
sum(pheno_PVEs) #Theoretically, this should be 1.
#choose K for PCs
pheno_RunElbow<-PCAForQTL::runElbow(prcompResult=pheno_prcomp)
print(paste0("phenotype Elbow: ", pheno_RunElbow))
pheno_K_elbow<-pheno_RunElbow
#RNGkind("L'Ecuyer-CMRG")
#set.seed(1)
#pheno_RunBE<-PCAForQTL::runBE(expr,B=20,alpha=0.05)
#print(paste0("phenotype BE: ", pheno_RunBE$numOfPCsChosen))
#pheno_K_BE<-pheno_RunBE$numOfPCsChosen
#PCAForQTL::makeScreePlot(pheno_prcomp,labels=c("Elbow","BE"),values=c(pheno_K_elbow,pheno_K_BE),titleText=tis)
#ggplot2::ggsave(paste0(prefix, "_pheno_PCs.jpg"), width=16, height=11, unit="cm")
# output phenotype PCs
pheno_PCs<-as.data.frame(pheno_PCs)
fwrite(pheno_PCs, file = paste0(prefix, "_pheno_PCs.tsv"), sep = "\t", quote = F, row.names=T)
# PVEs
pheno_importance<-as.data.frame(pheno_importance)
fwrite(pheno_importance, file = paste0(prefix, "_pheno_PVEs.tsv"), sep = "\t", quote = F, row.names=T)
# use Elbow cutoff
pheno_PCsTop<-pheno_PCs[,1:pheno_K_elbow]
fwrite(pheno_PCsTop, file = paste0(prefix, "_pheno_K_elbow.tsv"), sep = "\t", quote = F, row.names=T)
# use BE cutoff
#pheno_PCsTop<-pheno_PCs[,1:pheno_K_BE]
#fwrite(pheno_PCsTop, file = paste0(prefix, "_pheno_K_BE.tsv"), sep = "\t", quote = F, row.names=T)

# input genotype PCs
eigenvec<-fread(eigenvecfile, header = T, data.table = F)
rownames(eigenvec) <- eigenvec$IID
geno_PCs<-as.data.frame(eigenvec[,-(1:2)])
geno_PCs <- geno_PCs[rownames(pheno_PCsTop),]
colnames(geno_PCs) <- paste0("geno", colnames(geno_PCs))
fwrite(geno_PCs, file = paste0(prefix, "_geno_PCs.tsv"), sep = "\t", quote = F, row.names=T)
